config/routes.rb
NongteOa::Application.routes.draw do

  resources :conferences

  devise_for :admins

  root :to => "enterprises#index"

  resources :enterprises do
    member do
      get "add_receipt"
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
#  devise :database_authenticatable, :registerable,
#         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
          :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province
  has_many :countries
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  CONFERENCE_TYPES = [["类型1",1],["类型2",2],["类型3",3]]
end

app/models/content_person.rb
class ContentPerson < ActiveRecord::Base
  belongs_to :enterprise
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :city
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  has_many :content_persons, :dependent => :destroy
  has_many :enterprise_receipts, :dependent => :destroy
  accepts_nested_attributes_for :content_persons, :allow_destroy => :true,:reject_if => proc{ |attrs| attrs.all? { |k, v| v.blank? } }

  def province_city_country
    province = Province.find self.province_id
    city = City.find self.city_id
    country = Country.find self.country_id
    "#{province.title if province} #{city.title if city} #{country.title if country}"
  end


end

app/models/enterprise_receipt.rb
class EnterpriseReceipt < ActiveRecord::Base
  belongs_to :enterprise
end

app/models/oa_util.rb
# encoding: utf-8
class OaUtil
  # 省市联动数据
  #
  # 作者: 孙博
  # 最后更新时间: 2011-5-14
  #
  # ==== 示例
  #   OaUtil.address_data
  #
  # ==== 返回
  #   json 格式的
  #   { data : [
  #          {treeNode:'北京',value:1,childNode:[
  #              {treeNode:'东城区',value:11,childNode:[]},
  #              {treeNode:'西城区',value:12,childNode:[
  #                  {treeNode:'西城区1',value:121,childNode:[]},
  #                  {treeNode:'西城区2',value:122,childNode:[]}
  #                  ]
  #              }
  #              ]
  #          },
  #          {treeNode:'吉林',value:2,childNode:[
  #              {treeNode:'朝阳区',value:2-1,childNode:[]},
  #              {treeNode:'南关区',value:2-2,childNode:[
  #                  {treeNode:'南关区1',value:2-2-1,childNode:[]},
  #                  {treeNode:'南关区2',value:2-2-2,childNode:[]}
  #                  ]
  #              }
  #              ]
  #          }
  #      ]
  #  };
  #
  def self.address_data
#    address_data = OaUtil.get_config_value("address_data")
#    return address_data.html_safe if address_data
    provinces = Province.find :all,:include => :cities
    province_datas = []
    provinces.each do |province|
      city_datas = []
      province.cities.each do |city|
        country_datas = []
        city.countries.each do |country|
          country_datas << {:treeNode => country.title,:value => "#{province.id}-#{city.id}-#{country.id}",:childNode => []}
        end
        city_datas << {:treeNode => city.title,:value => "#{province.id}-#{city.id}",:childNode => country_datas}
      end
      province_datas << {:treeNode => province.title,:value => "#{province.id}",:childNode => city_datas}
    end
    result_json = province_datas.to_json.html_safe
#    OaUtil.set_config_value("address_data",result_json) and result_json
  end

end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :cities
end

app/models/util.rb
class Util
  def self.region_from_xml
    
  end

  def self.read_file(file_name)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'main'
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.xml
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.xml
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.xml
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.xml
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to(@conference, :notice => 'Conference was successfully created.') }
        format.xml  { render :xml => @conference, :status => :created, :location => @conference }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.xml
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to(@conference, :notice => 'Conference was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.xml
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to(conferences_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/enterprises_controller.rb
# coding: utf-8
class EnterprisesController < ApplicationController
  # GET /enterprises
  # GET /enterprises.xml
  def index
    @enterprises = Enterprise.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enterprises }
    end
  end

  # GET /enterprises/1
  # GET /enterprises/1.xml
  def show
    @enterprise = Enterprise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enterprise }
    end
  end

  # GET /enterprises/new
  # GET /enterprises/new.xml
  def new
    @enterprise = Enterprise.new
    content_persons = []
    content_persons[0] = ContentPerson.new
#    {"beijing"=>{"items"=>{"b-01-01"=>"010201"}, "val"=>"01"},"beijing"=>{"items"=>{"b-01-01"=>"010201"}, "val"=>"01"}}
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enterprise }
      format.js  { render_to_facebox}
    end
  end

  # GET /enterprises/1/edit
  def edit
    @enterprise = Enterprise.find(params[:id])
  end

  # POST /enterprises
  # POST /enterprises.xml
  def create
    @enterprise = Enterprise.new(params[:enterprise])

    respond_to do |format|
      if @enterprise.save
        format.html { redirect_to(@enterprise, :notice => 'Enterprise was successfully created.') }
        format.xml  { render :xml => @enterprise, :status => :created, :location => @enterprise }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enterprise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enterprises/1
  # PUT /enterprises/1.xml
  def update
    @enterprise = Enterprise.find(params[:id])

    respond_to do |format|
      if @enterprise.update_attributes(params[:enterprise])
        format.html { redirect_to(@enterprise, :notice => 'Enterprise was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enterprise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.xml
  def destroy
    @enterprise = Enterprise.find(params[:id])
    @enterprise.destroy

    respond_to do |format|
      format.html { redirect_to(enterprises_url) }
      format.xml  { head :ok }
    end
  end

  # 添加发票信息
  def add_receipt
    @enterprise = Enterprise.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/common/partials/_footer.html.erb
<footer id="bottom">
  <div class="wrapper">
    <nav>
      <a href="#">控制面板</a> &middot;
      <a href="#">企业管理</a> &middot;
      <a href="#">会议管理</a> &middot;
      <a href="#">Settings</a>
    </nav>
    <p>Copyright &copy; 2011 <b>
        <a HREF="kukuwuwu.info" title="kukuwuwu@sina.com">kukuwuwu</a></b></p>
  </div>
</footer>
<a href="#" id="totop">^ 回到最顶</a>

app/views/common/partials/_header.html.erb
<header id="top">
  <div class="wrapper">
    <div id="title">
      <%=image_tag "logo.png"%>
    </div>
    <div id="topnav">
      <a href="#">
        <%=image_tag "user_32.png", :class => "avatar"%></a>
				欢迎您登陆<b>孙博</b>
      <span>|</span> <a href="#">个人设置</a>
      <span>|</span> <a href="#">退出系统</a><br />
      <small>You have <a href="#" class="high"><b>0</b> new message!</a></small>
    </div>
    <!-- End of Top navigation -->
    <!-- Main navigation -->
    <nav id="menu">
      <ul class="sf-menu">
        <li><a HREF="dashboard.html">控制面板</a></li>
        <li class="<%= "current" if controller_name == "enterprises" %>">
          <%=link_to "企业管理", enterprises_path%>
          <ul>
            <li><%=link_to "企业管理", enterprises_path%></li>
            <li><a HREF="#">企业联系人管理</a></li>
          </ul>
        </li>
        <li>
          <a HREF="styles.html">会议管理</a>
          <ul>
            <li>
              <a HREF="styles.html">Basic Styles</a>
            </li>
            <li>
              <a href="#">Sample Pages...</a>
              <ul>
                <li><a HREF="samples-files.html">Files</a></li>
                <li><a HREF="samples-products.html">Products</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="<%= "current" if controller_name == "conferences" %>">
          <%= link_to "会议管理", conferences_path %>
        </li>
        <li><a HREF="#">管理员管理</a></li>
      </ul>
    </nav>
    <!-- End of Main navigation -->
    <!-- Aside links -->
    <aside><b>中文</b> &middot; <a href="#">English</a></aside>
    <!-- End of Aside links -->
  </div>
</header>

app/views/enterprises/_form.html.erb
<%= form_for(@enterprise) do |f| %>
  <% if @enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
        <% @enterprise.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :admin_id %><br />
    <%= f.text_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :industry_id %><br />
    <%= f.text_field :industry_id %>
  </div>
  <div class="field">
    <%= f.label :fax_num %><br />
    <%= f.text_field :fax_num %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br />
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :qq %><br />
    <%= f.text_field :qq %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_field :remark %>
  </div>
  <div class="field">
    <%= f.label :trademark %><br />
    <%= f.text_field :trademark %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_area :product %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>
  <div>
    <% @enterprise.content_persons.build %>
    <%=f.fields_for :content_persons do |content_person|%>
      <div>
        <%= content_person.label :name%><br />
        <%= content_person.text_field :name %>
      </div>
    <%end%>
    <%=f.fields_for :content_persons do |content_person|%>
      <div>
        <%= content_person.label :name%><br />
        <%= content_person.text_field :name %>
      </div>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enterprises/add_receipt.html.erb
<div id="page">
  <div class="wrapper">
    <%= form_for(@enterprise) do |f| %>
      <section class="column width3 first">
        <% if @enterprise.errors.any? %>
          <fieldset>
            <legend>Error message</legend>
            <div class="box box-error"><%= pluralize(@enterprise.errors.count, "error") %></div>
            <div class="box box-error-msg">
              <ol>
                <% @enterprise.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ol>
            </div>
          </fieldset>
        <% end %>
        <fieldset>
          <legend>企业信息</legend>
          <p>
            <%= f.label :title,"企业名称", :class => "required", :ACCESSKEY => "t"%><br/>
            <%= f.text_field :title%>&nbsp;<a href="#" class="btn btn-blue">验证重复</a>
          </p>
          <p>
            <%= f.label :province_id,"所在地", :class => "required"%><br/>
            <%= f.select :province_id, "<option value=\"0\">请选择</option>"%>
            <%= f.select :city_id, "<option value=\"0\">请选择</option>"%>
          </p>
          <p class="required">
            <%= f.label :industry_id,"行业类别", :class => "required"  %><br/>
            <%= f.text_field :industry_id%>
          </p>
          <p class="required">
            <%= f.label :fax_num,"传真", :class => "required"  %><br/>
            <%= f.text_field :fax_num%>
          </p>
          <p class="required">
            <%= f.label :phone_num,"电话", :class => "required"  %><br/>
            <%= f.text_field :phone_num%>
          </p>
          <p class="required">
            <%= f.label :address,"地址", :class => "required"  %><br/>
            <%= f.text_field :address%>
          </p>
          <p class="required">
            <%= f.label :zip_code,"邮编", :class => "required"  %><br/>
            <%= f.text_field :zip_code%>
          </p>
          <p class="required">
            <%= f.label :mail,"E-mail", :class => "required"  %><br/>
            <%= f.text_field :mail%>
          </p>
          <p class="required">
            <%= f.label :site,"网址", :class => "required"  %><br/>
            <%= f.text_field :site%>
          </p>
          <p class="required">
            <%= f.label :qq %><br/>
            <%= f.text_field :qq%>
          </p>
        </fieldset>
        <fieldset>
          <legend>操作</legend>
          <p>
            <%= f.submit "确认添加该企业", :class => "btn btn-green big"%>
            <%= f.submit "放弃并返回", :class => "btn btn-red big"%>
          </p>
        </fieldset>
      </section>

    <%end%>
  </div>
</div>

app/views/enterprises/edit.html.erb
<h1>Editing enterprise</h1>

<%= render :partial =>  'enterprises/partials/enterprise_new_form' %>

<%= link_to 'Show', @enterprise %> |
<%= link_to 'Back', enterprises_path %>

app/views/enterprises/index.html.erb
<div id="pagetitle">
  <div class="wrapper">
    <h1>企业管理</h1>
  </div>
</div>
<div id="page">
  <div class="wrapper">
    <section class="column width9 first">
      <h3>企业列表</h3>
      <div class="dataTables_filter">
        <%= link_to content_tag(:span, "", :class => "icon icon-add")+"添加新企业", new_enterprise_path, :class => "btn"%>
        <p/>
      </div>
      <table class="display stylized" id="example">
        <thead>
          <tr>
            <th width="20px">No.</th>
            <th width="120px">企业名称</th>
            <th width="60px">行业</th>
            <th width="100px">传真</th>
            <th width="100px">电话</th>
            <th>地址</th>
            <th width="120px">备注</th>
            <th width="120px">操作</th>
          </tr>
        </thead>
        <tbody>
          <% @enterprises.each do |enterprise| %>
            <tr class="gradeA <%= cycle("even", "odd")%>">
              <td><%= enterprise.id %></td>
              <td><%= enterprise.title %></td>
              <td><%= enterprise.industry_id %></td>
              <td><%= enterprise.fax_num %></td>
              <td><%= enterprise.phone_num %></td>
              <td><%= enterprise.address %></td>
              <td><%= enterprise.remark %></td>
              <td>
                <%= link_to '详细', enterprise %>
                <%= link_to '编辑', edit_enterprise_path(enterprise) %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
      <div class="dataTables_filter">
        <%= link_to content_tag(:span, "", :class => "icon icon-add")+"添加新企业", new_enterprise_path, :class => "btn"%>
        <p/>
      </div>
      <div class="clear">&nbsp;</div>
    </section>
  </div>
</div>
<%= javascript_include_tag "administry.js" %>

app/views/enterprises/new.html.erb
<div id="pagetitle">
  <div class="wrapper">
    <h1>企业管理 → <span>添加企业信息</span></h1>
  </div>
</div>
<div id="page">
  <div class="wrapper">
    <%= form_for(@enterprise) do |f| %>
      <section class="column width3 first">
        <fieldset>
          <legend>企业信息</legend>
          <p>
            <%= f.label :title,"企业名称", :class => "required", :ACCESSKEY => "t"%><br/>
            <%= f.text_field :title%>&nbsp;<a href="#" class="btn btn-blue">验证重复</a>
          </p>
          <p class="required">
            <%= f.label :industry_id,"行业类别", :class => "required"  %><br/>
            <%= f.text_field :industry_id%>
          </p>
          <p class="required">
            <%= f.label :fax_num,"传真", :class => "required"  %><br/>
            <%= f.text_field :fax_num%>
          </p>
          <p class="required">
            <%= f.label :phone_num,"电话", :class => "required"  %><br/>
            <%= f.text_field :phone_num%>
          </p>
          <p class="required">
            <%= f.label :zip_code,"邮编", :class => "required"  %><br/>
            <%= f.text_field :zip_code%>
          </p>
          <p class="required">
            <%= f.label :mail,"E-mail", :class => "required"  %><br/>
            <%= f.text_field :mail%>
          </p>
          <p class="required">
            <%= f.label :site,"网址", :class => "required"  %><br/>
            <%= f.text_field :site%>
          </p>
          <p class="required">
            <%= f.label :qq %><br/>
            <%= f.text_field :qq%>
          </p>
        </fieldset>
      </section>
      <section class="column width3">
        <fieldset>
          <legend>企业所在地及地址</legend>
          <p>
            <%= f.label :province_id,"所在地", :class => "required"%><br/>
            <%= f.select :province_id, "<option value=\"0\">请选择</option>"%>
            <%= f.select :city_id, "<option value=\"0\">请选择</option>"%>
            <%= f.select :country_id, "<option value=\"0\">请选择</option>"%>
          </p>
          <p>
            <%= f.label :address,"地址", :class => "required"  %><br/>
            <%= f.text_field :address%>
          </p>
        </fieldset>
        <fieldset>
          <legend>企业产品信息</legend>
          <p class="required">
            <%= f.label :trademark, "商标" %><br/>
            <%= f.text_field :trademark%>
          </p>
          <p class="required">
            <%= f.label :product, "产品", :class => "required"  %><br/>
            <%= f.text_field :product%>
          </p>
          <p class="required">
            <%= f.label :introduction, "简介" %><br/>
            <%= f.text_area :introduction, :class => "small full"%>
          </p>
          <p class="required">
            <%= f.label :remark,"企业备注" %><br/>
            <%= f.text_area :remark, :class => "small full"%>
          </p>
        </fieldset>
        <fieldset>
          <legend>标签tagTo</legend>
          <p>
            <textarea id="tags" class="small full tagInput" name="tags"></textarea>
          </p>
          <p>
            <span class="label label-blue">Blue</span>
            <span class="label label-blue">标记一</span>
            <span class="label label-blue">标记一</span>
            <span class="label label-blue">标记一</span>
            <span class="label label-blue">标记一</span>
            <span class="label label-blue">标记一标记一标记一</span>
            <span class="label label-red">已标记</span>
            <span class="label label-blue">Blue</span>
            <span class="label label-blue">Blue</span>
            <span class="label label-green">已标记</span>
            <span class="label label-blue">Blue</span>
          </p>
        </fieldset>
      </section>
      <section class="column width3">
        <fieldset>
          <legend>企业联系人</legend>
          <% @enterprise.content_persons.build %>
          <%=f.fields_for :content_persons do |content_person|%>
            <p>
              <%= content_person.label :name, "联系人姓名："%><br/>
              <%= content_person.text_field :name%>
            </p>
            <p>
              <%= content_person.label :position, "职务："%><br/>
              <%= content_person.text_field :position%>
            </p>
            <p>
              <%= content_person.label :phone_num, "联系电话："%><br/>
              <%= content_person.text_field :phone_num%>
            </p>
            <p>
              <%= content_person.label :fax_num, "传真："%><br/>
              <%= content_person.text_field :fax_num%>
            </p>
            <p>
              <%= content_person.label :mail, "邮箱："%><br/>
              <%= content_person.text_field :mail%>
            </p>
            <p>
              <%= content_person.label :address, "地址："%><br/>
              <%= content_person.text_field :address%>
            </p>
            <p>
              <%= content_person.label :zip_code, "邮编："%><br/>
              <%= content_person.text_field :zip_code%>
            </p>
            <p>
              <%= content_person.label :remark, "备注："%><br/>
              <%= content_person.text_field :remark%>
            </p>
          <%end%>
        </fieldset>
        <fieldset>
          <legend>操作</legend>
          <p>
            <%= f.submit "确认添加该企业", :class => "btn btn-green big"%>
            <%= f.submit "放弃并返回", :class => "btn btn-red big"%>
          </p>
        </fieldset>
      </section>
      <section class="column width2"></section>
    <%end%>
  </div>
</div>
<script language="javascript">
  window.mulSelectData = '<%= OaUtil.address_data %>';
  var mulSelects = [];
  var mulSelect = $(document).multilevelSelect({
    data : jQuery.parseJSON(window.mulSelectData),
    selects : ['#enterprise_province_id','#enterprise_city_id','#enterprise_country_id']
  });
  mulSelects.push(mulSelect);
</script>

app/views/enterprises/partials/_content_people_tr.html.erb
<tr>
  <td><%=content_people_tr.name%></td>
  <td><%=content_people_tr.sex%></td>
  <td><%=content_people_tr.position%></td>
  <td><%=content_people_tr.phone_num%></td>
  <td><%=content_people_tr.fax_num%></td>
  <td><%=content_people_tr.mail%></td>
  <td><%=content_people_tr.address%></td>
  <td><%=content_people_tr.remark%></td>
  <td>
    <%= link_to "详细信息" %>
    <%= link_to "编辑" %>
    <%= link_to "删除" %>
  </td>
</tr>

app/views/enterprises/partials/_enterprise_new_form.html.erb
<h1>New enterprise</h1>

<%= form_for(@enterprise) do |f| %>
  <% if @enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
        <% @enterprise.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :admin_id %><br />
    <%= f.text_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :industry_id %><br />
    <%= f.text_field :industry_id %>
  </div>
  <div class="field">
    <%= f.label :fax_num %><br />
    <%= f.text_field :fax_num %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br />
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :qq %><br />
    <%= f.text_field :qq %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_field :remark %>
  </div>
  <div class="field">
    <%= f.label :trademark %><br />
    <%= f.text_field :trademark %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_area :product %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>
  <div>
    <% @enterprise.content_persons.build %>
    <%=f.fields_for :content_persons do |content_person|%>
      <div>
        <%= content_person.label :name%><br />
        <%= content_person.text_field :name %>
      </div>
    <%end%>
    <%=f.fields_for :content_persons do |content_person|%>
      <div>
        <%= content_person.label :name%><br />
        <%= content_person.text_field :name %>
      </div>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', enterprises_path %>

app/views/enterprises/partials/_receipt_tr.html.erb
<tr>
  <td><%=content_people_tr.name%></td>
  <td><%=content_people_tr.sex%></td>
  <td><%=content_people_tr.position%></td>
  <td><%=content_people_tr.phone_num%></td>
  <td><%=content_people_tr.fax_num%></td>
  <td><%=content_people_tr.mail%></td>
  <td><%=content_people_tr.address%></td>
  <td><%=content_people_tr.remark%></td>
  <td>
    <%= link_to "详细信息" %>
    <%= link_to "编辑" %>
    <%= link_to "删除" %>
  </td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NongteOa</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>